### ISSUE TITLE
input validation for quantity text filed

### ISSUE THREAD

**Issue by jaa6** [henaraihan/SmartCafe#21]
![issue1](https://user-images.githubusercontent.com/47186814/53083115-bd6bf680-3517-11e9-83c6-58d5215c17ee.PNG)

Here is the prob

**Comment by jaa6** [comment]
![issue2](https://user-images.githubusercontent.com/47186814/53083420-569b0d00-3518-11e9-9a73-bb32bc3b1bc6.PNG)

**Comment by henaraihan** [comment]
Issue is resolved
